export const site = {
  name: "Andre Huizen",
  legalName: "Laurentius Andre Cornelis Rudolf Huizen",
  title: "Scientific machine learning researcher and software builder",
  description:
    "Researching scientific machine learning, physics-informed models, partial differential equations, numerical simulation, and computer vision.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://andre-huizen.vercel.app",
  github: "https://github.com/anesticia",
  orcid: "https://orcid.org/0009-0002-0300-9169",
  doi: "https://doi.org/10.30864/jsi.v18i1.601",
} as const;

export type WorkKind = "research" | "software" | "experiment" | "fork";
export type WorkStatus = "active" | "completed" | "exploratory" | "archived";

export type Work = {
  slug: string;
  title: string;
  eyebrow: string;
  summary: string;
  description: string[];
  kind: WorkKind;
  status: WorkStatus;
  year: string;
  topics: string[];
  technologies: string[];
  contribution: string;
  image?: string;
  imageAlt?: string;
  sourceUrl?: string;
  sourceLabel?: string;
  featured: boolean;
  public: boolean;
  lastVerified: string;
  facts: { label: string; value: string }[];
};

export const works: Work[] = [
  {
    slug: "reaction-diffusion",
    title: "Reaction–diffusion systems",
    eyebrow: "PDE simulation · Research",
    summary: "A two-track study of reusable reaction–diffusion simulation and physics-only long-horizon Gray–Scott approximation.",
    description: [
      "This research code explores Gray–Scott, Brusselator, Schnakenberg, and custom two-species kinetics on periodic domains. The solver separates stiff diffusion from nonlinear reaction dynamics using Fourier pseudo-spectral spatial discretization and Cox–Matthews ETDRK4 time integration.",
      "A parallel benchmark compares six spectral and finite-difference schemes using pattern similarity, wall time, throughput, and peak GPU memory. The work connects mathematical modelling, numerical analysis, and visually interpretable scientific computing.",
    ],
    kind: "research",
    status: "active",
    year: "2026",
    topics: ["PDE", "Numerical methods", "Pattern formation", "SciML"],
    technologies: ["Python", "NumPy", "PyTorch", "FFT", "ETDRK4"],
    contribution: "Designed the general simulator, configurable kinetics, GPU-capable numerical benchmark, and reproducible output pipeline.",
    image: "/images/reaction-diffusion.bf11faa839ec.webp",
    imageAlt: "Labyrinth-like reaction–diffusion pattern generated by the simulator",
    featured: true,
    public: false,
    lastVerified: "2026-08-22",
    facts: [
      { label: "Model", value: "Two coupled reaction–diffusion PDEs" },
      { label: "Reference method", value: "Fourier pseudo-spectral + ETDRK4" },
      { label: "Benchmark", value: "6 numerical schemes" },
      { label: "Long-horizon record", value: "18 runs across t = 200–9000" },
    ],
  },
  {
    slug: "orbit-pinn",
    title: "Shared Structure-Preserving Local Flow",
    eyebrow: "ORBIT-PINN V5 series · Research",
    summary: "A shared structure-preserving local neural flow for charged-particle trajectories across three magnetic-field families.",
    description: [
      "The ORBIT-PINN experiment series decomposes a long trajectory into local time windows. Each window uses Fourier time features, hard continuity transforms, and automatic differentiation to preserve state across the horizon.",
      "The physics objective combines kinematic and Lorentz-force residuals with an energy invariant. The design is aimed at reducing long-horizon optimization difficulty while keeping the learned path physically interpretable.",
    ],
    kind: "research",
    status: "active",
    year: "2026",
    topics: ["PINN", "Lorentz dynamics", "Neural ODE", "SciML"],
    technologies: ["Python", "PyTorch", "Automatic differentiation"],
    contribution: "Developed the rolling micro-window formulation, hard inter-window continuity, and physics-residual architecture.",
    image: "/images/research/orbit-architecture.webp",
    imageAlt: "Current shared structure-preserving local-flow architecture from the ORBIT-PINN V5 experiment series",
    featured: true,
    public: false,
    lastVerified: "2026-08-22",
    facts: [
      { label: "Dynamics", value: "Charged particle in a magnetic field" },
      { label: "V4 evidence", value: "31 complete, 4 fallback, 1 failed" },
      { label: "Latest gate", value: "V5 PCGrad pilot failed" },
    ],
  },
  {
    slug: "wave-pinn-thesis",
    title: "Wave propagation with PINNs",
    eyebrow: "Undergraduate thesis · Research",
    summary: "A completed thesis comparing physics-informed acoustic wave fields with FDTD across homogeneous and heterogeneous media.",
    description: [
      "The thesis notebooks study wave propagation through homogeneous and layered heterogeneous media. They compare physics-informed predictions with finite-difference time-domain references across reflection, refraction, and longer propagation horizons.",
      "The repository contains experiment notebooks, generated animations, numerical snapshots, and comparison figures. It is represented here as ongoing research rather than a finished performance claim.",
    ],
    kind: "research",
    status: "completed",
    year: "2025–2026",
    topics: ["PINN", "Wave equation", "FDTD", "Heterogeneous media"],
    technologies: ["Python", "Jupyter", "DeepXDE", "NumPy"],
    contribution: "Built the experimental notebooks, numerical references, comparison workflow, and research visualizations.",
    image: "/images/wave-pinn.688595129c57.webp",
    imageAlt: "FDTD and PINN wave-field snapshots through layered heterogeneous media",
    featured: true,
    public: false,
    lastVerified: "2026-08-22",
    facts: [
      { label: "Reference", value: "Finite-difference time-domain" },
      { label: "Learning method", value: "Physics-informed neural network" },
      { label: "Media", value: "Homogeneous and heterogeneous" },
      { label: "Hardest case", value: "70.04% final relative L2" },
    ],
  },
  {
    slug: "object-classification-paper",
    title: "Object classification through edge features",
    eyebrow: "Published paper · 2023",
    summary: "Combining Sobel, Canny, Roberts, histogram features, and Random Forest for traffic-image classification.",
    description: [
      "This peer-reviewed study evaluates how edge-detection features and intensity histograms affect a Random Forest image classifier. It was published in Jurnal Sistem dan Informatika, volume 18, issue 1.",
      "The combined edge-only pipeline reported 72.78% accuracy. Adding histogram features produced a reported 99.75% result on the study split. The publication page and DOI remain the canonical sources for the full methodology and limitations.",
    ],
    kind: "research",
    status: "completed",
    year: "2023",
    topics: ["Computer vision", "Random Forest", "Feature engineering"],
    technologies: ["Python", "Image processing", "Ensemble learning"],
    contribution: "Sole-author study covering method design, implementation, evaluation, and publication.",
    sourceUrl: "https://doi.org/10.30864/jsi.v18i1.601",
    sourceLabel: "Read the paper",
    featured: false,
    public: true,
    lastVerified: "2026-08-22",
    facts: [
      { label: "Venue", value: "Jurnal Sistem dan Informatika 18(1)" },
      { label: "Pages", value: "58–63" },
      { label: "DOI", value: "10.30864/jsi.v18i1.601" },
    ],
  },
];

export const publication = {
  title: "Optimalisasi Klasifikasi Objek Melalui Integrasi Metode Ensemble dan Teknik Ekstraksi Fitur Deteksi Tepi",
  authors: [site.legalName],
  venue: "Jurnal Sistem dan Informatika (JSI)",
  year: 2023,
  volume: "18",
  issue: "1",
  pages: "58–63",
  doi: "10.30864/jsi.v18i1.601",
  url: site.doi,
};
