export const site = {
  name: "Andre Huizen",
  legalName: "Laurentius Andre Cornelis Rudolf Huizen",
  title: "Scientific machine learning researcher and software builder",
  description:
    "Researching scientific machine learning, physics-informed models, partial differential equations, numerical simulation, and computer vision.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://andre-huizen.vercel.app",
  github: "https://github.com/anesticia",
  orcid: "https://orcid.org/0009-0002-0300-9169",
  doi: "https://doi.org/10.30864/jsi.v18i1.601",
} as const;

export type WorkKind = "research" | "software" | "experiment" | "fork";
export type WorkStatus = "active" | "completed" | "exploratory" | "archived";

export type Work = {
  slug: string;
  title: string;
  eyebrow: string;
  summary: string;
  description: string[];
  kind: WorkKind;
  status: WorkStatus;
  year: string;
  topics: string[];
  technologies: string[];
  contribution: string;
  image?: string;
  imageAlt?: string;
  sourceUrl?: string;
  sourceLabel?: string;
  featured: boolean;
  public: boolean;
  lastVerified: string;
  facts: { label: string; value: string }[];
};

export const works: Work[] = [
  {
    slug: "reaction-diffusion",
    title: "Reaction–diffusion systems",
    eyebrow: "PDE simulation · Research",
    summary: "A general two-species simulator for studying how local reaction laws produce global pattern formation.",
    description: [
      "This research code explores Gray–Scott, Brusselator, Schnakenberg, and custom two-species kinetics on periodic domains. The solver separates stiff diffusion from nonlinear reaction dynamics using Fourier pseudo-spectral spatial discretization and Cox–Matthews ETDRK4 time integration.",
      "A parallel benchmark compares six spectral and finite-difference schemes using pattern similarity, wall time, throughput, and peak GPU memory. The work connects mathematical modelling, numerical analysis, and visually interpretable scientific computing.",
    ],
    kind: "research",
    status: "active",
    year: "2026",
    topics: ["PDE", "Numerical methods", "Pattern formation", "SciML"],
    technologies: ["Python", "NumPy", "PyTorch", "FFT", "ETDRK4"],
    contribution: "Designed the general simulator, configurable kinetics, GPU-capable numerical benchmark, and reproducible output pipeline.",
    image: "/images/reaction-diffusion.bf11faa839ec.webp",
    imageAlt: "Labyrinth-like reaction–diffusion pattern generated by the simulator",
    featured: true,
    public: false,
    lastVerified: "2026-07-13",
    facts: [
      { label: "Model", value: "Two coupled reaction–diffusion PDEs" },
      { label: "Reference method", value: "Fourier pseudo-spectral + ETDRK4" },
      { label: "Benchmark", value: "6 numerical schemes" },
    ],
  },
  {
    slug: "orbit-pinn",
    title: "ORBIT-PINN",
    eyebrow: "Physics-informed learning · Research",
    summary: "A rolling-window physics-informed neural model for long-horizon charged-particle trajectories.",
    description: [
      "ORBIT-PINN decomposes a long trajectory into local time windows. Each window uses Fourier time features, hard continuity transforms, and automatic differentiation to preserve state across the horizon.",
      "The physics objective combines kinematic and Lorentz-force residuals with an energy invariant. The design is aimed at reducing long-horizon optimization difficulty while keeping the learned path physically interpretable.",
    ],
    kind: "research",
    status: "active",
    year: "2026",
    topics: ["PINN", "Lorentz dynamics", "Neural ODE", "SciML"],
    technologies: ["Python", "PyTorch", "Automatic differentiation"],
    contribution: "Developed the rolling micro-window formulation, hard inter-window continuity, and physics-residual architecture.",
    image: "/images/orbit-pinn.829609fe7a3c.webp",
    imageAlt: "Architecture diagram for the rolling-window ORBIT-PINN model",
    featured: true,
    public: false,
    lastVerified: "2026-07-13",
    facts: [
      { label: "Dynamics", value: "Charged particle in a magnetic field" },
      { label: "Training", value: "Rolling local time windows" },
      { label: "Constraints", value: "Kinematics, dynamics, and energy" },
    ],
  },
  {
    slug: "wave-pinn-thesis",
    title: "Wave propagation with PINNs",
    eyebrow: "Undergraduate thesis · Research",
    summary: "Comparing physics-informed neural solutions with finite-difference wave propagation in heterogeneous media.",
    description: [
      "The thesis notebooks study wave propagation through homogeneous and layered heterogeneous media. They compare physics-informed predictions with finite-difference time-domain references across reflection, refraction, and longer propagation horizons.",
      "The repository contains experiment notebooks, generated animations, numerical snapshots, and comparison figures. It is represented here as ongoing research rather than a finished performance claim.",
    ],
    kind: "research",
    status: "active",
    year: "2025–2026",
    topics: ["PINN", "Wave equation", "FDTD", "Heterogeneous media"],
    technologies: ["Python", "Jupyter", "DeepXDE", "NumPy"],
    contribution: "Built the experimental notebooks, numerical references, comparison workflow, and research visualizations.",
    image: "/images/wave-pinn.688595129c57.webp",
    imageAlt: "FDTD and PINN wave-field snapshots through layered heterogeneous media",
    featured: true,
    public: false,
    lastVerified: "2026-07-13",
    facts: [
      { label: "Reference", value: "Finite-difference time-domain" },
      { label: "Learning method", value: "Physics-informed neural network" },
      { label: "Media", value: "Homogeneous and heterogeneous" },
    ],
  },
  {
    slug: "codex-chess-lab",
    title: "Codex Chess Lab",
    eyebrow: "Engine research · Software",
    summary: "An independent C++ UCI chess engine with paired benchmarking, a browser arena, and learned evaluation experiments.",
    description: [
      "Codex Chess Lab is an evidence-led engine research platform. It contains an independent C++ engine, registered-engine live analysis, deterministic match tooling, Stockfish teacher-data generation, and linear and neural evaluation paths.",
      "Promotions require paired games and confidence gates. Failed experiments remain documented instead of being rewritten as successes. Version 0.3.0 is stronger than its preserved Python baseline but is explicitly not presented as Stockfish-level.",
    ],
    kind: "software",
    status: "active",
    year: "2026",
    topics: ["Game AI", "Search", "Benchmarking", "Neural evaluation"],
    technologies: ["C++", "Python", "UCI", "PyTorch"],
    contribution: "Built the clean-room engine, research protocol, evaluation pipeline, arena, and reproducible promotion gates.",
    featured: false,
    public: false,
    lastVerified: "2026-07-13",
    facts: [
      { label: "Current engine", value: "CodexEngine 0.3.0" },
      { label: "Protocol", value: "Paired games with confidence gates" },
      { label: "Platform", value: "C++ UCI engine + Python research tools" },
    ],
  },
  {
    slug: "geoguesser-engine",
    title: "GeoGuesser Engine",
    eyebrow: "Computer vision · Software",
    summary: "A local-first, explainable image-geolocation assistant with license-aware data foundations.",
    description: [
      "The engine is designed to rank likely locations from street-level imagery while surfacing the visual and textual clues behind each estimate. The current baseline combines optional OCR, script and language hints, a small gazetteer, country priors, and visual retrieval metadata.",
      "The project emphasizes compliant dataset collection. Its manifest-first pipeline records source licenses, attribution, route-aware splits, duplicate checks, and quality reports. It is a research and practice assistant—not a live-game automation client.",
    ],
    kind: "software",
    status: "active",
    year: "2026",
    topics: ["Computer vision", "Geolocation", "Explainability", "Data governance"],
    technologies: ["Python", "FastAPI", "SQLite", "PyTorch"],
    contribution: "Designed the API, explainable baseline, storage model, licensed-data pipeline, and compliance boundaries.",
    featured: false,
    public: false,
    lastVerified: "2026-07-13",
    facts: [
      { label: "Current milestone", value: "M4 dataset foundation" },
      { label: "Interface", value: "Local FastAPI service" },
      { label: "Dataset policy", value: "Licensed, attributed, and auditable" },
    ],
  },
  {
    slug: "object-classification-paper",
    title: "Object classification through edge features",
    eyebrow: "Published paper · 2023",
    summary: "Combining Sobel, Canny, Roberts, histogram features, and Random Forest for traffic-image classification.",
    description: [
      "This peer-reviewed study evaluates how edge-detection features and intensity histograms affect a Random Forest image classifier. It was published in Jurnal Sistem dan Informatika, volume 18, issue 1.",
      "The combined edge-only pipeline reported 72.78% accuracy. Adding histogram features produced a reported 99.75% result on the study split. The publication page and DOI remain the canonical sources for the full methodology and limitations.",
    ],
    kind: "research",
    status: "completed",
    year: "2023",
    topics: ["Computer vision", "Random Forest", "Feature engineering"],
    technologies: ["Python", "Image processing", "Ensemble learning"],
    contribution: "Sole-author study covering method design, implementation, evaluation, and publication.",
    sourceUrl: "https://doi.org/10.30864/jsi.v18i1.601",
    sourceLabel: "Read the paper",
    featured: false,
    public: true,
    lastVerified: "2026-07-13",
    facts: [
      { label: "Venue", value: "Jurnal Sistem dan Informatika 18(1)" },
      { label: "Pages", value: "58–63" },
      { label: "DOI", value: "10.30864/jsi.v18i1.601" },
    ],
  },
  {
    slug: "desktop-gremlin",
    title: "Desktop Gremlin experiments",
    eyebrow: "Fork exploration · Software",
    summary: "A C# WPF desktop-pet fork used to explore animation, interaction, packaging, and Windows behavior.",
    description: [
      "This public repository is a fork, not an original upstream project. It is included transparently as a software exploration involving WPF sprite behavior, configuration, and Windows desktop integration.",
      "The archive distinguishes this contribution type from original research projects so that experimentation remains visible without overstating authorship.",
    ],
    kind: "fork",
    status: "exploratory",
    year: "2026",
    topics: ["Desktop UI", "Animation", "Windows"],
    technologies: ["C#", "WPF", ".NET"],
    contribution: "Explored and adapted an upstream desktop-pet codebase; upstream authorship is retained.",
    sourceUrl: "https://github.com/anesticia/Desktop_Gremlin",
    sourceLabel: "View fork",
    featured: false,
    public: true,
    lastVerified: "2026-07-13",
    facts: [
      { label: "Ownership", value: "Public fork" },
      { label: "Platform", value: "Windows desktop" },
      { label: "Framework", value: "C# WPF" },
    ],
  },
  {
    slug: "scientific-code-reading",
    title: "Scientific code reading shelf",
    eyebrow: "Fork archive · References",
    summary: "A public collection of upstream SciML, simulation, and notebook projects studied as technical references.",
    description: [
      "The public GitHub account includes forks of DeepXDE, Simwave, the Physics-based Deep Learning book, Marimo, and a Turing-pattern repository. These entries document areas of technical study and do not imply upstream authorship.",
      "They are grouped into one archive record to preserve the complete public footprint without allowing reference forks to dominate the original-work portfolio.",
    ],
    kind: "fork",
    status: "exploratory",
    year: "2026",
    topics: ["SciML", "Wave simulation", "Reactive notebooks"],
    technologies: ["Python", "DeepXDE", "Marimo"],
    contribution: "Maintained personal forks for study and experimentation; all upstream project ownership remains with original maintainers.",
    sourceUrl: "https://github.com/anesticia?tab=repositories",
    sourceLabel: "Browse GitHub",
    featured: false,
    public: true,
    lastVerified: "2026-07-13",
    facts: [
      { label: "Type", value: "Grouped public forks" },
      { label: "Themes", value: "SciML, simulation, notebooks" },
      { label: "Attribution", value: "Upstream ownership preserved" },
    ],
  },
];

export const publication = {
  title: "Optimalisasi Klasifikasi Objek Melalui Integrasi Metode Ensemble dan Teknik Ekstraksi Fitur Deteksi Tepi",
  authors: [site.legalName],
  venue: "Jurnal Sistem dan Informatika (JSI)",
  year: 2023,
  volume: "18",
  issue: "1",
  pages: "58–63",
  doi: "10.30864/jsi.v18i1.601",
  url: site.doi,
};
